import { useStudioStore } from '../../store'
import type { ExportableBenchmarkDataset } from '../../types/optimization'

function avg(values: number[]): number {
  if (values.length === 0) return 0
  return values.reduce((a, b) => a + b, 0) / values.length
}

/** LaTeX special-character escape map, ordered so backslash is handled first. */
const TEX_ESCAPE_MAP: [RegExp, string][] = [
  [/\\/g, '\\textbackslash{}'],
  [/&/g, '\\&'],
  [/_/g, '\\_'],
  [/#/g, '\\#'],
  [/\$/g, '\\$'],
  [/%/g, '\\%'],
  [/\{/g, '\\{'],
  [/\}/g, '\\}'],
  [/~/g, '\\textasciitilde{}'],
  [/\^/g, '\\textasciicircum{}'],
]

/**
 * Escape a string for safe inclusion in a LaTeX document.
 * Backslashes are replaced first to prevent double-escaping.
 */
function escapeTex(raw: string): string {
  let s = raw
  for (const [pattern, replacement] of TEX_ESCAPE_MAP) {
    s = s.replace(pattern, replacement)
  }
  return s
}

export function ExportSurface() {
  const { benchmarkResults } = useStudioStore()

  if (benchmarkResults.length === 0) {
    return (
      <div className="panel-card p-4 border-slate-700/40">
        <p className="text-sm text-slate-500 italic">
          Run benchmarks first to enable exports.
        </p>
      </div>
    )
  }

  function buildDataset(): ExportableBenchmarkDataset {
    const runs = benchmarkResults
    const compressionRatios = runs.map((r) => r.report.delta.compressionRatio ?? 0)
    return {
      exportedAt: new Date().toISOString(),
      runs,
      summary: {
        totalCircuits: runs.length,
        avgGateCountReduction: avg(runs.map((r) => r.report.delta.gateCountReduction)),
        avgDepthReduction: avg(runs.map((r) => r.report.delta.depthReduction)),
        avgCompressionRatio: avg(compressionRatios),
      },
    }
  }

  function triggerDownload(content: string, filename: string, mime: string) {
    const blob = new Blob([content], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  function exportJSON() {
    const dataset = buildDataset()
    triggerDownload(JSON.stringify(dataset, null, 2), `rqm-benchmark-${Date.now()}.json`, 'application/json')
  }

  function exportCSV() {
    const rows: string[] = []
    rows.push(
      [
        'circuitId', 'name', 'category', 'backend', 'baseline',
        'originalGateCount', 'optimizedGateCount', 'gateCountReduction',
        'originalDepth', 'optimizedDepth', 'depthReduction',
        'compressionRatio', 'geodesicReduction', 'fidelity', 'equivalent',
      ].join(','),
    )
    for (const r of benchmarkResults) {
      const { definition: def, report } = r
      rows.push(
        [
          def.circuitId, `"${def.name}"`, def.category, def.backend, def.baseline,
          report.original.gateCount, report.optimized.gateCount, report.delta.gateCountReduction,
          report.original.depth, report.optimized.depth, report.delta.depthReduction,
          report.delta.compressionRatio?.toFixed(4) ?? '',
          report.delta.geodesicReduction?.toFixed(4) ?? '',
          report.invariants.fidelity?.toFixed(8) ?? '',
          report.invariants.equivalent ?? '',
        ].join(','),
      )
    }
    triggerDownload(rows.join('\n'), `rqm-benchmark-${Date.now()}.csv`, 'text/csv')
  }

  function exportLatex() {
    const lines: string[] = [
      '% RQM Optimization Benchmark Results',
      '% Generated by RQM Studio',
      `% ${new Date().toISOString()}`,
      '',
      '\\begin{table}[h]',
      '\\centering',
      '\\caption{RQM Optimization Results}',
      '\\label{tab:rqm-results}',
      '\\begin{tabular}{llrrrrrr}',
      '\\hline',
      'Circuit & Category & Qubits & Gate $\\Delta$ & Depth $\\Delta$ & Compression & Fidelity & Equiv. \\\\',
      '\\hline',
    ]
    for (const r of benchmarkResults) {
      const { definition: def, report } = r
      const gateD = report.delta.gateCountReduction > 0
        ? `-${report.delta.gateCountReduction}`
        : `${report.delta.gateCountReduction}`
      const depthD = report.delta.depthReduction > 0
        ? `-${report.delta.depthReduction}`
        : `${report.delta.depthReduction}`
      const comp = report.delta.compressionRatio !== undefined
        ? `${(report.delta.compressionRatio * 100).toFixed(1)}\\%`
        : '—'
      const fid = report.invariants.fidelity !== undefined
        ? report.invariants.fidelity.toFixed(6)
        : '—'
      const equiv = report.invariants.equivalent ? '\\checkmark' : '\\times'
      lines.push(
        `${escapeTex(def.name)} & ${escapeTex(def.category)} & ${def.qubitCount} & ${gateD} & ${depthD} & ${comp} & ${fid} & ${equiv} \\\\`,
      )
    }
    lines.push('\\hline')
    lines.push('\\end{tabular}')
    lines.push('\\end{table}')
    triggerDownload(lines.join('\n'), `rqm-benchmark-${Date.now()}.tex`, 'text/plain')
  }

  const dataset = buildDataset()

  return (
    <div className="flex flex-col gap-4">
      {/* Summary */}
      <div className="panel-card p-4">
        <h3 className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">
          Run Summary
        </h3>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <p className="text-xs text-slate-500">Circuits</p>
            <p className="text-lg font-mono text-slate-200">{dataset.summary.totalCircuits}</p>
          </div>
          <div>
            <p className="text-xs text-slate-500">Avg Gate Reduction</p>
            <p className="text-lg font-mono text-green-400">
              {dataset.summary.avgGateCountReduction.toFixed(1)}
            </p>
          </div>
          <div>
            <p className="text-xs text-slate-500">Avg Depth Reduction</p>
            <p className="text-lg font-mono text-green-400">
              {dataset.summary.avgDepthReduction.toFixed(1)}
            </p>
          </div>
          <div>
            <p className="text-xs text-slate-500">Avg Compression</p>
            <p className="text-lg font-mono text-teal-400">
              {(dataset.summary.avgCompressionRatio * 100).toFixed(1)}%
            </p>
          </div>
        </div>
      </div>

      {/* Export buttons */}
      <div className="panel-card p-4">
        <h3 className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">
          Export
        </h3>
        <div className="flex flex-col gap-2">
          <button
            onClick={exportJSON}
            className="w-full py-2 text-sm rounded border transition-all
              border-cyan-600/50 text-cyan-400 bg-cyan-500/10
              hover:bg-cyan-500/20 hover:border-cyan-500/60"
          >
            ↓ Export JSON
          </button>
          <button
            onClick={exportCSV}
            className="w-full py-2 text-sm rounded border transition-all
              border-teal-600/50 text-teal-400 bg-teal-500/10
              hover:bg-teal-500/20 hover:border-teal-500/60"
          >
            ↓ Export CSV
          </button>
          <button
            onClick={exportLatex}
            className="w-full py-2 text-sm rounded border transition-all
              border-purple-600/50 text-purple-400 bg-purple-500/10
              hover:bg-purple-500/20 hover:border-purple-500/60"
          >
            ↓ Export Paper Table (.tex)
          </button>
        </div>
        <p className="text-xs text-slate-500 mt-2 leading-relaxed">
          Exports include all run results with metrics, traces, and invariant checks.
          The .tex table is IEEE/QCE-ready.
        </p>
      </div>

      {/* Shareable note */}
      <div className="panel-card p-4 border-slate-600/30">
        <h3 className="text-xs font-semibold uppercase tracking-widest text-slate-500 mb-2">
          Shareable Run Links
        </h3>
        <p className="text-xs text-slate-500 leading-relaxed">
          Shareable URLs require backend persistence.
          {/* TODO: implement when backend storage is available */}
          State model is ready — connect a storage adapter to enable this feature.
        </p>
      </div>
    </div>
  )
}

